In [10]:
import numpy as np
import pandas as pd

In [20]:
shoes = pd.read_csv('ShoesDatabaseFinalCsv.csv')

In [21]:
shoes.head()

,shoeId,shoeBrand,shoeCategory,shoeColour,shoeImage,shoePrice
0,1,BEAUTIFEET,"Shoes,Women's Shoes,Clothing,All Women's Shoes","Multicolor,MULTI",https://i5.walmartimages.com/asr/3990181c-1f37...,10.00
1,2,BEAUTIFEET,"Shoes,Women's Shoes,Clothing,All Women's Shoes","Multicolor,MULTI",https://i5.walmartimages.com/asr/3990181c-1f37...,8.00
2,3,Caparros,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Silver,https://i5.walmartimages.com/asr/a07174df-7c83...,79.00
3,4,Caparros,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Silver,https://i5.walmartimages.com/asr/a07174df-7c83...,31.99
4,5,Caparros,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Silver,https://i5.walmartimages.com/asr/a07174df-7c83...,7.99

In [22]:
print(shoes.shape)

(8475, 6)

In [23]:
shoes.duplicated().sum()

2156

In [24]:
shoes

,shoeId,shoeBrand,shoeCategory,shoeColour,shoeImage,shoePrice
0,1,BEAUTIFEET,"Shoes,Women's Shoes,Clothing,All Women's Shoes","Multicolor,MULTI",https://i5.walmartimages.com/asr/3990181c-1f37...,10.00
1,2,BEAUTIFEET,"Shoes,Women's Shoes,Clothing,All Women's Shoes","Multicolor,MULTI",https://i5.walmartimages.com/asr/3990181c-1f37...,8.00
2,3,Caparros,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Silver,https://i5.walmartimages.com/asr/a07174df-7c83...,79.00
3,4,Caparros,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Silver,https://i5.walmartimages.com/asr/a07174df-7c83...,31.99
4,5,Caparros,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Silver,https://i5.walmartimages.com/asr/a07174df-7c83...,7.99
...,...,...,...,...,...,...
8470,AVsRmQUrnnc1JgDc36Pe,Unbranded,"Clothing,Shoes,Women's Shoes,All Women's Shoes",Black,https://i5.walmartimages.com/asr/0d21eafd-8de8...,10.83
8471,AVsRmQUrnnc1JgDc36Pe,Unbranded,"Clothing,Shoes,Women's Shoes,All Women's Shoes",Black,https://i5.walmartimages.com/asr/0d21eafd-8de8...,10.48
8472,AVsRobK8QMlgsOJE61dD,Big Buddha,"Clothing,Shoes,Women's Shoes,All Women's Shoes","BLACK,TAUPE",https://i5.walmartimages.com/asr/cb374697-cfef...,22.87
8473,AVsRobNlQMlgsOJE61dE,Big Buddha,"Clothing,Shoes,Women's Shoes,All Women's Shoes",COGNAC,https://i5.walmartimages.com/asr/65771db9-a15c...,19.72
8474,AVsTXsEoQMlgsOJE69UA,Big Buddha,"Clothing,Shoes,Women's Shoes,All Women's Shoes","BLACK,Taupe",https://i5.walmartimages.com/asr/03c1f5aa-142f...,19.88