In [17]:
import numpy as np
import pandas as pd

In [19]:
shoes = pd.read_csv('ShoeDatabase.csv')

In [20]:
shoes.head()

,shoeId,shoeBrand,shoeCategory,shoeColour,shoeImage,shoePrice
0,1,BEAUTIFEET,"Shoes,Women's Shoes,Clothing,All Women's Shoes","Multicolor,MULTI",https://i5.walmartimages.com/asr/3990181c-1f37...,10.00
1,2,Caparros,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Silver,https://i5.walmartimages.com/asr/a07174df-7c83...,79.00
2,3,Vince Camuto,"Shoes,Women's Shoes,Clothing,All Women's Shoes",Brown,https://i5.walmartimages.com/asr/59a1b430-299b...,159.00
3,4,Michael Kors,"Women's Shoes,Boots",Black,http://i.ebayimg.com/images/g/IycAAOSwvUlWshVZ...,180.00
4,5,Faded Glory,"Shoes,Clothing,Women's Shoes,All Women's Shoes","TAN,Grey",http://i5.walmartimages.com/dfw/dce07b8c-e5c0/...,29.97

In [21]:
print(shoes.shape)

(672, 6)

In [22]:
shoes.duplicated().sum()

0

In [23]:
shoes

,shoeId,shoeBrand,shoeCategory,shoeColour,shoeImage,shoePrice
0,1,BEAUTIFEET,"Shoes,Women's Shoes,Clothing,All Women's Shoes","Multicolor,MULTI",https://i5.walmartimages.com/asr/3990181c-1f37...,10.00
1,2,Caparros,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Silver,https://i5.walmartimages.com/asr/a07174df-7c83...,79.00
2,3,Vince Camuto,"Shoes,Women's Shoes,Clothing,All Women's Shoes",Brown,https://i5.walmartimages.com/asr/59a1b430-299b...,159.00
3,4,Michael Kors,"Women's Shoes,Boots",Black,http://i.ebayimg.com/images/g/IycAAOSwvUlWshVZ...,180.00
4,5,Faded Glory,"Shoes,Clothing,Women's Shoes,All Women's Shoes","TAN,Grey",http://i5.walmartimages.com/dfw/dce07b8c-e5c0/...,29.97
...,...,...,...,...,...,...
667,668,Barefooters,"Shoes,Women's Shoes,Clothing,All Women's Shoes",Beige,https://i5.walmartimages.com/asr/2481ed9c-969a...,105.00
668,669,Grendene,"Clothing,Shoes,Women's Shoes,All Women's Shoes","Green,Lilac,Purple Pink",https://i5.walmartimages.com/asr/5ec7b188-d0ae...,26.99
669,670,Beacon Shoes,"Shoes,Slip-ons,Women's Shoes,Clothing,All Wome...","Black Lamy Polyurethane,Sand Lamy Polyurethane",https://i5.walmartimages.com/asr/7d47bef4-1b28...,49.95
670,671,DF by Dearfoams,"Clothing,Shoes,Women's Shoes,All Women's Shoes","Pewter Dots,Black Dots",https://i5.walmartimages.com/asr/dd774972-3f3d...,7.47
671,672,Big Buddha,"Clothing,Shoes,Women's Shoes,All Women's Shoes","BLACK,TAUPE",https://i5.walmartimages.com/asr/cb374697-cfef...,22.87

In [24]:
import pickle
pickle.dump(shoes, open('shoes.pkl','wb'))