In [2]:
import numpy as np
import pandas as pd

In [3]:
shoes = pd.read_csv('ShoeDatabaseFinal.csv')

In [4]:
shoes.head()

,shoeId,shoeBrand,shoeCategory,shoeColour,shoeImage,shoePrice
0,1,Caparros,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Silver,https://i5.walmartimages.com/asr/a07174df-7c83...,79.00
1,2,Vince Camuto,"Shoes,Women's Shoes,Clothing,All Women's Shoes",Brown,https://i5.walmartimages.com/asr/59a1b430-299b...,159.00
2,3,JBU by Jambu,"Shoes,Women's Shoes,Clothing,All Women's Shoes",Brown,https://i5.walmartimages.com/asr/7bd8cdef-d6aa...,69.00
3,4,Style & Co.,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Beige,https://i5.walmartimages.com/asr/aaf29b0f-1084...,19.99
4,5,Ellen Tracy,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Beige,https://i5.walmartimages.com/asr/3dc9c088-f9f0...,21.99

In [5]:
print(shoes.shape)

(440, 6)

In [6]:
shoes.duplicated().sum()

0

In [7]:
shoes

,shoeId,shoeBrand,shoeCategory,shoeColour,shoeImage,shoePrice
0,1,Caparros,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Silver,https://i5.walmartimages.com/asr/a07174df-7c83...,79.00
1,2,Vince Camuto,"Shoes,Women's Shoes,Clothing,All Women's Shoes",Brown,https://i5.walmartimages.com/asr/59a1b430-299b...,159.00
2,3,JBU by Jambu,"Shoes,Women's Shoes,Clothing,All Women's Shoes",Brown,https://i5.walmartimages.com/asr/7bd8cdef-d6aa...,69.00
3,4,Style & Co.,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Beige,https://i5.walmartimages.com/asr/aaf29b0f-1084...,19.99
4,5,Ellen Tracy,"Shoes,Clothing,Women's Shoes,All Women's Shoes",Beige,https://i5.walmartimages.com/asr/3dc9c088-f9f0...,21.99
...,...,...,...,...,...,...
435,436,Barefooters,"Shoes,Women's Shoes,Clothing,All Women's Shoes",Beige,https://i5.walmartimages.com/asr/2481ed9c-969a...,105.00
436,437,Grendene,"Clothing,Shoes,Women's Shoes,All Women's Shoes","Green,Lilac,Purple Pink",https://i5.walmartimages.com/asr/5ec7b188-d0ae...,26.99
437,438,Beacon Shoes,"Shoes,Slip-ons,Women's Shoes,Clothing,All Wome...","Black Lamy Polyurethane,Sand Lamy Polyurethane",https://i5.walmartimages.com/asr/7d47bef4-1b28...,49.95
438,439,DF by Dearfoams,"Clothing,Shoes,Women's Shoes,All Women's Shoes","Pewter Dots,Black Dots",https://i5.walmartimages.com/asr/dd774972-3f3d...,7.47
439,440,Big Buddha,"Clothing,Shoes,Women's Shoes,All Women's Shoes","BLACK,TAUPE",https://i5.walmartimages.com/asr/cb374697-cfef...,22.87

In [10]:
import pickle
from collections import defaultdict 
pickle.dump(shoes, open('shoes.pkl','wb'))
pickle.dump(defaultdict(set), open('userCart.pkl','wb'))